apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
  labels:
    app: api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
        - name: api-app
          image: 127.0.0.1:53565/api-app:latest
          ports:
            - containerPort: 3000
          # env:
          #   - name: ASPNETCORE_ENVIRONMENT
          #     value: "Production"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: 127.0.0.1:53565/web-app:latest
          ports:
            - containerPort: 5005
          # env:
          #   - name: ASPNETCORE_ENVIRONMENT
          #     value: "Production"

# kubectl apply -f deployment.yml

# kubectl create deployment api-app --image=muayadoh/api-app:latest
# kubectl create deployment web-app --image=muayadoh/web-app:latest
