networks:
  internal-network:
    name: "${REGISTRY}_internal-network"
    driver: bridge

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.Nginx
    container_name: nginx-container
    depends_on:
      - api-app
      - web-app
    networks:
      - internal-network
    ports:
      - "80:80"
      # - "443:443"
  
  redis:
    build:
      context: .
      dockerfile: Dockerfile.Redis
    container_name: redis-container
    networks:
      - internal-network
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    restart: always

  api-app:
    image: "${REGISTRY}/api-app:latest"
    container_name: "api-app-container"
    networks:
      - internal-network
    ports:
      - "3001:3001"
    restart: always

  web-app:
    image: "${REGISTRY}/web-app:latest"
    container_name: "web-app-container"
    networks:
      - internal-network
    ports:
      - "5005:5005"
    restart: always
