networks:
  internal-network:
    name: "${REGISTRY}_internal-network"
    driver: bridge

volumes:
  grafana-data:
  
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.Nginx
    container_name: nginx-container
    depends_on:
      - api-app
      - web-app
    networks:
      - internal-network
    ports:
      - "80:80"
      # - "443:443"
  
  redis:
    build:
      context: .
      dockerfile: Dockerfile.Redis
    container_name: redis-container
    networks:
      - internal-network
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    restart: always

  api-app:
    image: "${REGISTRY}/api-app:latest"
    container_name: "api-app-container"
    networks:
      - internal-network
    ports:
      - "3000:3000"
    restart: always

  web-app:
    image: "${REGISTRY}/web-app:latest"
    container_name: "web-app-container"
    networks:
      - internal-network
    ports:
      - "5005:5005"
    restart: always
  
  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile.Prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - internal-network

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile.Grafana
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3001:3000"
    networks:
      - internal-network
    depends_on:
      - prometheus

  node-exporter:
    build:
      context: ./node-exporter
      dockerfile: Dockerfile.NodeExporter
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)"
    ports:
      - "9100:9100"
    networks:
      - internal-network

  cadvisor:
    build:
      context: ./cadvisor
      dockerfile: Dockerfile.Cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8081:8080"
    networks:
      - internal-network
