networks:
  internal-network:
    driver: bridge

volumes:
  jenkins_home:
  registry-data:

services:
  # Local Docker Registry
  registry:
    image: registry:2
    container_name: local-registry
    restart: unless-stopped
    ports:
      - "5006:5000"  # Access via http://localhost:5006/v2/_catalog
    volumes:
      - registry-data:/var/lib/registry
    networks:
      - internal-network

  # Jenkins
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.Jenkins
    container_name: jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"      # Jenkins UI Access via http://localhost:8080
      - "50000:50000"    # Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to use Docker on the host
      - ./jenkins:/jenkins                         # Optional: Jenkins pipeline files or jobs
    networks:
      - internal-network
