networks:
  internal-network:
    name: "${REGISTRY}_internal-network"
    driver: bridge

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.Nginx
    container_name: nginx-container
    depends_on:
      - api-app
      - web-app
    networks:
      - internal-network
    ports:
      - "80:80"
      - "443:443"

  api-app:
    image: "${REGISTRY}/api-app:latest"
    container_name: "api-app-container"
    networks:
      - internal-network
    restart: always

  web-app:
    image: "${REGISTRY}/web-app:latest"
    container_name: "web-app-container"
    networks:
      - internal-network
    restart: always
