# Use the official Jenkins LTS image with JDK 17
FROM jenkins/jenkins:lts-jdk17

# Switch to root user to install additional packages if needed
USER root

# Install recommended packages (optional)
RUN apt-get update && \
    apt-get install -y git curl vim docker.io  && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Switch back to Jenkins user
USER jenkins

# Expose Jenkins ports
EXPOSE 8080 50000

# Set default command
CMD ["/usr/bin/tini", "--", "/usr/local/bin/jenkins.sh"]
