apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    app: jenkins
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - name: ui        # Name is required
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: agent     # Name is required
      protocol: TCP
      port: 50000
      targetPort: 50000

# minikube service jenkins-service
