apiVersion: v1
kind: Service
metadata:
  name: api-app-service
  labels:
    app: api-app
spec:
  type: LoadBalancer
  selector:
    app: api-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  labels:
    app: web-app
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005

# kubectl apply -f service.yml
# minikube service api-app-service
