global:
  scrape_interval: 5s  # how often to scrape targets

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Scrape Node Exporter for host metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # Scrape cAdvisor for Docker container metrics
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "api-app"
    static_configs:
      - targets: ["api-app:3000"]

  - job_name: "web-app"
    static_configs:
      - targets: ["web-app:5005"]
